### ISSUE TITLE
How to help

### ISSUE THREAD

**Issue by dukex** [nodeschool/saopaulo#1]
Hi @thebergamo 
How to I can help you?

**Comment by thebergamo** [comment]
Hi @dukex !

Our first event are date for 14/07 you can help us being a monitor =D What you say?

(Acho que aqui especificamente seria mais fácil falarmos em PT-BR não?)

**Comment by dukex** [comment]
Opa! 
Qual é o papel do monitor? eu trabalho na consolação, perto de onde vai ser o evento.

**Comment by thebergamo** [comment]
O tutor básicamente vai ajudar a galerinha que estiver com dúvidas enquanto estiverem realizando o curso =D

**Comment by dukex** [comment]
Me mantem informado, meu gtalk é duke.m16 at gmail

**Comment by thebergamo** [comment]
blzinha =D se quiser estamos montando um slack pra comunidade

**Comment by alanhoff** [comment]
Slack? E a #nodebr? :-(

## 

Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-07-02 1:15 GMT-03:00 Marcos Vinicius Bérgamo notifications@github.com
:

**Comment by dukex** [comment]
@thebergamo manda ai o slack

**Comment by thebergamo** [comment]
@alanhoff é o slack da nodebr :smile: 

http://nodebr.slack.com

**Comment by paulohp** [comment]
@thebergamo me add nesse slack ai:

tarallo.php@gmail.com

**Comment by alanhoff** [comment]
Mas ninguém mais usa o slack, queria centralizar as conversar no IRC, o que
acham?

## 

Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-07-02 11:13 GMT-03:00 Paulo Pires notifications@github.com:

**Comment by dukex** [comment]
@alanhoff eu curto bem mais IRC, mais facil e mais simples e não precisa de alguem cadastrando como no slack, mas parece que é uma onda crescente da galera mudando para o slack

**Comment by alanhoff** [comment]
Já temos uma canal na freenode.net, chamado #nodebr

## 

Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

Em 2 de julho de 2015 11:58, Duke notifications@github.com escreveu:

**Comment by thebergamo** [comment]
@dukex posso contar com você amanhã?

**Comment by dukex** [comment]
@thebergamo pode sim!
