### ISSUE TITLE
Mentor Registration for July 6th, 2019 

### ISSUE THREAD

**Issue by ErickWendel** [nodeschool/saopaulo#10]
Hello everybody 👋!

Faculdade Impacta is hosting us on July 06th from 1 pm - 5 pm!. The address is: Impacta Certificação e Treinamento - Avenida Paulista, 1009 - 17º andar. Auditório. -- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:

Have already completed the core NodeSchool workshoppers (https://nodeschool.io) before the event.
Having also completed elective workshoppers (https://nodeschool.io) is a great bonus.
Review the Mentor Best Practices wiki page.
Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

**Confirmed mentors (limited to 10 mentors)**:

* You?
* [x] @dev-celestino 
* [x] @igorhalfeld
* [x] @victorperin 
* [x] @kamilahsantos
* [x] @woliveiras
* [x] @icarcal 
* [x] @leandro-machado
* [x] @msrmarcio
* [x] @amirelemam
* [x] @lancaluis 

**Organizers**:

  @ErickWendel 
  @khaosdoctor

Thanks for joining! 🙌

Attendee registration link: https://www.meetup.com/pt-BR/nodeschoolsp/events/261811632/

**Comment by ErickWendel** [comment]
@igorhalfeld @icarcal let's do it?

**Comment by IgorHalfeld** [comment]
Let's make it happen! 🎉

**Comment by manoel-freitas** [comment]
Mannn i want to do make this happen to \o/ nodeschool is really great \o/ and i promise that i will buy another glasses for the day of the meetup

**Comment by victorperin** [comment]
Me adiciona como mentor aí, @ErickWendel :)

**Comment by Kamilahsantos** [comment]
Hi, I would like to be a mentor at the event :)

**Comment by woliveiras** [comment]
Podem me adicionar como mentor, @ErickWendel e @khaosdoctor?

Conseguimos levar meus alunos do Heliópolis neste evento lindão?

**Comment by khaosdoctor** [comment]
Opa @woliveiras consegue sim! Só precisa pedir para eles se registrarem lá no evento do meetup, se não nós não conseguimos liberar o acesso no prédio

**Comment by khaosdoctor** [comment]
Importante dizer @woliveiras que o pessoal precisa estar, de fato, nos confirmados do meetup, a lista de espera não tem as infos também, só dá esse toque para eles se registrarem o quanto antes

**Comment by icarcal** [comment]
Boa galera, posso ser mentor também!

**Comment by leandropittondo** [comment]
Bacana! 
Gostaria de ser mentor, pode me adicionar?

**Comment by msrmarcio** [comment]
Vou completar a bagaça aí campeão e tu me add depois @msrmarcio

**Comment by ErickWendel** [comment]
**LEIAM A DESCRIÇÃO SOBRE O QUE UM MENTOR DEVE FAZER** 

Galera, a maioria dos estudantes ficarão trabalhando nos workshoppers do site da [nodeschool.io](nodeschool.io). Peço que entrem e façam algum exercicios pois vamos tirar duvidas sobre como podem seguir.

Leiam tbm nosso wiki aqui no github sobre como denunciar problemas de conduta (de acordo com nosso codigo de conduta)

**Comment by lancaluis** [comment]
Opa! Me add como mentor pfv! Bora ajudar a galera :) @ErickWendel @khaosdoctor

**Comment by amirelemam** [comment]
Hey! Can you add me to be a mentor, please? :D @ErickWendel @khaosdoctor 
Thx

**Comment by ErickWendel** [comment]
Guys, I've reached our mentor's limit! Please, if you couldn't go, send me a message here to remove you and add more people. From this comment, we're starting our mentors' waiting list

**Comment by khaosdoctor** [comment]
> **LEIAM A DESCRIÇÃO SOBRE O QUE UM MENTOR DEVE FAZER**
> 
> Galera, a maioria dos estudantes ficarão trabalhando nos workshoppers do site da [nodeschool.io](nodeschool.io). Peço que entrem e façam algum exercicios pois vamos tirar duvidas sobre como podem seguir.
> 
> Leiam tbm nosso wiki aqui no github sobre como denunciar problemas de conduta (de acordo com nosso codigo de conduta)

Complementando essa resposta, leiam o guia de boas práticas de mentoria: https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices

**Comment by msrmarcio** [comment]
Workshoppers concluidos
]

start eletivas
________________________________
De: Erick Wendel <notifications@github.com>
Enviado: quarta-feira, 29 de maio de 2019 12:51
Para: nodeschool/saopaulo
Cc: Marcio Rodrigues; Mention
Assunto: [nodeschool/saopaulo] Mentor Registration for July 6th, 2019 (#10)


Hello everybody 👋!

Faculdade Impacta is hosting us on July 06th from 1 pm - 5 pm!. The address is: Impacta Certificação e Treinamento - Avenida Paulista, 1009 - 17º andar. Auditório. -- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:

Have already completed the core NodeSchool workshoppers (https://nodeschool.io) before the event.
Having also completed elective workshoppers (https://nodeschool.io) is a great bonus.
Review the Mentor Best Practices wiki page.
Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

Confirmed mentors:

  *   You?
  *    @manoeljosefneto<https://github.com/manoeljosefneto>
  *    @IgorHalfeld<https://github.com/IgorHalfeld>
  *    @victorperin<https://github.com/victorperin>
  *    @Kamilahsantos<https://github.com/Kamilahsantos>
  *    @woliveiras<https://github.com/woliveiras>
  *    @icarcal<https://github.com/icarcal>
  *    @leandro-machado<https://github.com/leandro-machado>
  *    @msrmarcio<https://github.com/msrmarcio>

Organizers:

@ErickWendel<https://github.com/ErickWendel>
@khaosdoctor<https://github.com/khaosdoctor>

Thanks for joining! 🙌

Attendee registration link: https://www.meetup.com/pt-BR/nodeschoolsp/events/261811632/

**Comment by khaosdoctor** [comment]
Apenas um lembrete:
@manoeljosefneto
@IgorHalfeld
@victorperin
@Kamilahsantos
@woliveiras
@icarcal
@leandro-machado
@msrmarcio
@amirelemam
@lancaluis

Temos um guia de mentoria, ele pode ajudar vocês a entenderem melhor os processos: https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices

**Comment by ErickWendel** [comment]
Friends just a reminder. If someone here didn’t put the RG on the meetup RSVP unfortunately you wouldn’t ender tomorrow. Please sent us a DM on twitter if you didn’t put your name there
