### ISSUE TITLE
Call4papers for July 06th - Workshop focused session

### ISSUE THREAD

**Issue by ErickWendel** [nodeschool/saopaulo#11]
Hello everybody 👋! We're accepting workshop proposals until 10th, June.

Faculdade Impacta is hosting us on July 06th from 1 pm - 5 pm!. The address is: Impacta Certificação e Treinamento - Avenida Paulista, 1009 - 17º andar. Auditório. -- Comment to get involved or ask questions.

Link: https://www.meetup.com/pt-BR/nodeschoolsp/events/261811632/

If this is your first time speaking and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

As an Instructor you should:
- Present a hands-on lab for at least 2:30hr

Please submit your Ideas below following the pattern: 

*Title*:

*Description*:
*Time*: 
*Requirements*: 
*Language*: pt-br or en-us
*Instructor mini bio*:
*Instructor Links*:
- Link 1
- Link 2
- Link 3

# Talk Selected! 
Edit1: The selected workshop session was Title: Server Side Rendering for Artist - Audiovisual Creative Apps with Next.js - @elihugarret 🎉🎉🎉

**Comment by albertbit8** [comment]
Title: Conhecendo o fremework Nest.js

Description: Como criar uma API com nest.js
Time: de 3 horas.
Requirements: Entender o básico do protocolo Htttp e básico de JavaScript
Language: pt-br
Instructor mini bio: Ex Publicitario que se arriscou na area de Tecnologia a 5 anos atras e nunca mais saiu.
Já trabalhou em faculdade, consultorias, bancos e atualmente esta numa empresa do ramo de crypto-ativos. 
É entusiasta blockchain e esta cursando pós em Inteligencia Artificial.
Acredita que todo mundo pode criar uma versão melhor de si mesmo.
Instructor Links: linkedin https://www.linkedin.com/in/albertbitencourte/

**Comment by glaucia86** [comment]
**Title:** Todo-List em Vue.Js - Zero to Deploy

**Description:** Nesse workshop vocês aprenderão de uma maneira bastante prática como criar um Todo-List em Vue.js e como fazer um deploy/host prático usando o App Service!
Time: de 3 horas.
**Requirements:** Entender o básico do protocolo HTML, Css & JavaScript - Curso: **[AQUI](http://bit.ly/2H2VOfS)**
Language: pt-br
**Instructor mini bio:** Glaucia Lemos é Regional Cloud Advocate LATAM 🥑 na Microsoft. Ama realizar contribuições em projetos Open Source. Atua como Member & Contributor no Node.js Foundation e no React Community realizando contribuições nas traduções do site Nodejs.org e Reactjs.org para o português.Também atua como: Community Leader & Tech Speaker do Meetup Coders in Rio , Technical Author no Portal iMasters e Volunteer & Tech Speaker do WoMakersCode.
**Instructor Links:** https://glaucialemos.netlify.com/contact/

**Comment by renatoromao** [comment]
Title: Integrando seus Office Apps com aplicações externas usando JavaScript + Office Add-Ins

Description: Muitas vezes temos trabalhos manuais e repetitivos durante nosso dia a dia, além de duplicar informações muitas vezes que poderiam estar centralizadas em um determinado lugar. Com o Office Add-In, é possível você integrar suas ferramentas Excel, Word, PowerPoint, Outlook, OneNote e Project, em aplicações externas, podendo interagir com informações preenchidas nestes aplicativos do Office, e vice-versa.
Time: 2h30 até 3h
Requirements: Básico em Html, Css e JavaScript; 
Language: pt-br
Instructor mini bio: Renato Romão, Líder Técnico e Desenvolvedor de Soluções pela Go-IT, associado no MTAC Brasil contribuindo com a comunidade técnica, Co-Organizador do CaquiCoders no Vale do Paraíba/SP.
Instructor Links: 
- LinkedIn: https://www.linkedin.com/in/renatoromao
- Blog: https://renatooromao.wordpress.com
- Facebook: https://www.facebook.com/renatooromaoo

**Comment by amirelemam** [comment]
Title: Hands-on lab: How to structure your API

Description: In this lab, we'll create an API and structure it in a way to isolate responsibilities and make the code files easier to understand.
Time: 2h30
Requirements: Fundamentals of Node.js and basic MongoDB
Language: en-us
Instructor mini bio: BSc. in Biomedical Informatics from University of Sao Paulo (USP), I code in Node.js for over 2 years, currently focused on Healthcare.
Instructor Links:
LinkedIn: https://www.linkedin.com/in/amirelemam/

**Comment by amirelemam** [comment]
Title: Hands-on lab: How to structure your API

Description: In this lab, we'll create an API and structure it in a way to isolate responsibilities and make the code files simpler.
Time: 2h30
Requirements: Fundamentals of Node.js and basic MongoDB
Language: en-us
Instructor mini bio: BSc. Biomedical Informatician at University of Sao Paulo (USP) as a Student of Excellence, I program in Node.js for over 2 years, currently focusing on IoT for Health (IoMT).
Instructor Links:
LinkedIn: https://www.linkedin.com/in/amirelemam/

**Comment by elihugarret** [comment]
**Title**: Server Side Rendering for Artist - Audiovisual Creative Apps with Next.js

**Description**: In this workshop you will learn how to create and manipulate music, visuals, MIDI and OSC from the server, bypassing the chrome-only experimental features and using whatever browser you choose only using Next.js the SSR React framework.
**Time**: 2h
**Requiements**: Basic knowledge in Node and React. Interest in digital and modern art.
**Language**: en-us and a little bit of pt-br.
**Instructor mini bio**: Elihú Garrett is a Mexican living in Brasil. B.Math in Mathematical Engineering by Instituto Politécnico Nacional (Ciudad de México, México), B.Lit in Lenguas y Literaturas Hispánicas by UNAM (Ciudad de México, México), multimedia artist, lecturer and front-end developer. 
**Instructor Links**:
https://elihu.soy/
https://twitter.com/Mr_Auk

**Comment by ErickWendel** [comment]
Time to vote folks! Please share the link with your friends. The most liked workshop will be chosen later \o/

**Comment by ErickWendel** [comment]
@elihugarret brother you didn’t RSVP on our meetup and we must send your document to the place. Please DM us on Twitter or send on email. If you wouldn’t send until 5pm unfortunately we’ll have to find another person to make de session
