### ISSUE TITLE
Mentor Registration for September 21st, 2019

### ISSUE THREAD

**Issue by khaosdoctor** [nodeschool/saopaulo#14]
Hello everybody 👋!

Faculdade Impacta is hosting us on September 07th from 1 pm - 5 pm!. The address is: Impacta Certificação e Treinamento - Avenida Paulista, 1009 - 17º andar. Auditório. -- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:

- Have already completed the core NodeSchool workshoppers (https://nodeschool.io) before the event.
- Having also completed elective workshoppers (https://nodeschool.io) is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

**Confirmed mentors (limited to 10 mentors)**:

- [ ] @lancaluis
- [ ] @Kamilahsantos
- [ ] @amirelemam 
- [ ] @WellsSA

**Organizers**:

  @ErickWendel 
  @khaosdoctor

Thanks for joining! 🙌

Attendee registration link: https://www.meetup.com/nodeschoolsp/events/263786026

**Comment by lancaluis** [comment]
I wanna be a mentor again! Could you add me? 😜

**Comment by Kamilahsantos** [comment]
hi, i wanna be a mentor again :smiley: . Could you add me?

**Comment by amirelemam** [comment]
Hi! I'd like to be a mentor again, please! 😄

**Comment by WellsSA** [comment]
Hey! I'd like to be a mentor too! That's my first time! \o/

**Comment by khaosdoctor** [comment]
This event has been canceled due to scheduling problems with the auditorium where we'd host it. More information in the e-mail we've sent you :)
