### ISSUE TITLE
Call4papers for September 21st- Workshop focused session

### ISSUE THREAD

**Issue by khaosdoctor** [nodeschool/saopaulo#15]
Hello everybody 👋! We're accepting workshop proposals until 10th, June.

Faculdade Impacta is hosting us on September 07th from 1 pm - 5 pm!. The address is: **Impacta Certificação e Treinamento - Avenida Paulista, 1009 - 17º andar. Auditório.** -- Comment to get involved or ask questions.

Link: https://www.meetup.com/nodeschoolsp/events/263786026/

If this is your first time speaking and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

As an Instructor you should:
- Present a hands-on lab for at least 2:30hr

Please submit your Ideas below following the pattern: 

*Title*:

*Description*:
*Time*: 
*Requirements*: 
*Language*: pt-br or en-us
*Instructor mini bio*:
*Instructor Links*:
- Link 1
- Link 2
- Link 3

**Comment by IgorHalfeld** [comment]
**Title:** Filters like a boss
**Description:** Como criar filtros pra sua API? quero mostrar como fazemos criar filtros por qualquer campo sendo ele genérico. Ex: `/api/users?search=(name[eq]:'Igor')&sort=-1&limit=20`
**Time:** 2hs
**Requirements:** Ter mexido já com express, koa...
**Language:** pt-br
**Instructor mini bio:** Software Engineer focused on Front-end engineering and architecture and I'm building stuff at Estratégia Consursos, Microsoft MVP, Organizer at Vue.js Summit, Co-Organizer at Vue.js SP, JSSP and NodeBR Meetup... 
**Instructor Links:**
https://github.com/igorhalfeld
https://igorluiz.me/
https://www.linkedin.com/in/igorhalfeld/

**Comment by khaosdoctor** [comment]
This event has been canceled due to scheduling problems with the auditorium where we'd host it. More information in the e-mail we've sent you :)
