### ISSUE TITLE
Mentor Registration: NodeSchool São Paulo at São Paulo, Brazil

### ISSUE THREAD

**Issue by khaosdoctor** [nodeschool/saopaulo#16]
Hello mentors! Our next event will be held at **São Paulo, Brazil** on **September 7th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

👋

-----

#### Mentors

- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*

#### Organizers and volunteers

- [ ] @Fauntleroy
- [ ] @itsmed

**Comment by takempf** [comment]
@khaosdoctor don't forget to change the usernames under "Organizers and volunteers"!

**Comment by khaosdoctor** [comment]
yeap! Sorry about this @Fauntleroy, I was testing the script, but I forgot I added the key 😅 It's all good now! Thanks for the heads up!
