### ISSUE TITLE
Mentor Registration for November 2nd

### ISSUE THREAD

**Issue by khaosdoctor** [nodeschool/saopaulo#24]
Hello everybody 👋!

Our next event will be held at **Caelum SP** on **November 2nd from 1-6PM**. Chime in on this issue to join us as a mentor for this event!

-- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:

- Have already completed the core NodeSchool workshoppers (http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers (http://nodeschool.io/#workshopper-list) is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

**Confirmed mentors (limited to 10 mentors)**:

* @amirelemam 
* @Kamilahsantos
* @victorperin

**Organizers**:

  @ErickWendel
  @khaosdoctor

Thanks for joining! 🙌

[Attendee registration link](https:&#x2F;&#x2F;www.meetup.com&#x2F;nodeschoolsp&#x2F;events&#x2F;265451047)

**Comment by amirelemam** [comment]
@amirelemam

**Comment by Kamilahsantos** [comment]
Hi, I would like to be mentor again :)

**Comment by victorperin** [comment]
I'm here and want to help again :)

**Comment by mc4rol9** [comment]
Hi. I have never mentored before, but I am available and would like to. I am able to complete the workshoppers until the event date. Just let me know. 
Thank you.

**Comment by khaosdoctor** [comment]
@mc4rol9 let's do it!
