### ISSUE TITLE
Mentor Registration for December 14th

### ISSUE THREAD

**Issue by khaosdoctor** [nodeschool/saopaulo#31]
Hello everybody 👋!

Our next event will be held at **Impacta Tecnologia** on **December 14th from 1-5PM**. Chime in on this issue to join us as a mentor for this event!

-- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:

- Have already completed the core NodeSchool workshoppers (http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers (http://nodeschool.io/#workshopper-list) is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

**Confirmed mentors (limited to 10 mentors)**:

* @IgorHalfeld
* @onlurking

**Organizers**:

  @ErickWendel
  @khaosdoctor
  @victorperin 

Thanks for joining! 🙌

[Attendee registration link](https:&#x2F;&#x2F;www.meetup.com&#x2F;nodeschoolsp&#x2F;events&#x2F;266164611)

**Comment by victorperin** [comment]
![image](https://user-images.githubusercontent.com/5847145/68080476-d92fd800-fdda-11e9-9778-335807e4f85d.png)

**Comment by IgorHalfeld** [comment]
![image](https://user-images.githubusercontent.com/9022134/68537550-d128e880-0344-11ea-9a86-b03a827d1107.png)

**Comment by onlurking** [comment]
![AirBrush_20191129225931](https://user-images.githubusercontent.com/10618352/69894257-f97c8500-12fb-11ea-8bc9-09675c79caff.jpg)
