### ISSUE TITLE
Mentor Registration for February 8th

### ISSUE THREAD

**Issue by khaosdoctor** [nodeschool/saopaulo#33]
Hello everybody 👋!

Our next event will be held at **Caelum Ensino e Inovação** on **February 8th from 1-6PM**. Chime in on this issue to join us as a mentor for this event!

-- Comment to get involved or ask questions.

If this is your first time mentoring and are in doubt, we're sure you can! Just leave us a comment and we'll help you in any way we can.

Mentors should:

- Have already completed the core NodeSchool workshoppers (http://nodeschool.io/#workshopper-list) before the event.
- Having also completed elective workshoppers (http://nodeschool.io/#workshopper-list) is a great bonus.
- Review the [Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).
- Arrive 30 minutes early (12:30p) so we can get set up and have our mentor meeting.

**Confirmed mentors (limited to 10 mentors)**:
* @Kamilahsantos
* @lucasmarques73
* @thierrysantos
* @rjmunhoz
* @gbarska
* You?

**Organizers**:

  @ErickWendel
  @khaosdoctor
  @victorperin 
  

Thanks for joining! 🙌

[Attendee registration link](https:&#x2F;&#x2F;www.meetup.com&#x2F;nodeschoolsp&#x2F;events&#x2F;267493201&#x2F;)

**Comment by victorperin** [comment]
![image](https://user-images.githubusercontent.com/5847145/71563139-73be3780-2a69-11ea-8400-b839bb19051c.png)

**Comment by Kamilahsantos** [comment]
Hi,
I would like to be a mentor again :smile:

**Comment by lucasmarques73** [comment]
Hey,
I'd like to be a mentor.

**Comment by 0xthierry** [comment]
Hey,
I'd like to be a mentor.That's my first time!

**Comment by roziscoding** [comment]
I'm in!
Let's do this 😉

**Comment by gbarska** [comment]
Hi guys I would like to be a mentor 😃

**Comment by khaosdoctor** [comment]
Awesome! Checking you in :)
