### ISSUE TITLE
New Organizers

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/saopaulo#4]
Hello @nodeschool/sao-paolo !

There was just a request in https://github.com/nodeschool/organizers/issues/382 to create a Sao-Paolo chapter ... _(slightly awkward)_ ... by @ErickWendel and @Leolosi . I think it would be good if you could work together at future Sao Paolo events!

Note: I have not added @ErickWendel or @Leolosi to the Chapter Team. @thebergamo Would you mind to add them to https://github.com/orgs/nodeschool/teams/sao-paolo and make them part of Node.js Sao Paolo?

**Comment by thebergamo** [comment]
Hello @martinheidegger !!

I've talked with @ErickWendel on messenger this afternoon :)

We will organize a meetup on next month and after that publishing here the results of the event.

**Comment by thebergamo** [comment]
Hey @martinheidegger could you add @ErickWendel to @nodeschool organization? Then I can add him to Sao Paulo team.

He is very active in Brazilian communities and he wants to take care about nodeschool in SP and I have trust that he will do an awesome job :)

Thanks in advance!
